### ISSUE TITLE
No default: config file (default is path/config.yaml|json|toml)

### ISSUE THREAD

**Issue by justin-calleja** [spf13/hugo#579] opened 2014-10-24 17:17 UTC
Although the help says "config file (default is path/config.yaml|json|toml)", it is not picked up by default.

InitializeConfig() in hugo.go has CfgFile == ""

I am running `hugo server --watch` from project dir and get:

"ERROR: 2014/10/24 Config not found... using only defaults, stuff may not work"

Regards,
Justin

**Comment by anthonyfok** [comment] 2015-01-18 04:04
Hi @justin-calleja,

> In project dir, running ../hugo/hugo gives me:
>
>     project$ ../hugo/hugo
>     ERROR: 2014/11/01 Config not found... using only defaults, stuff may not work
>     ERROR: 2014/11/01 Unable to find Static Directory: /Users/justin/go-stuff/hugo-issue/hugo/static/
>     CRITICAL: 2014/11/01 No source directory found, expecting to find it at /Users/justin/go-stuff/hugo-issue/hugo/content

That `../hugo/hugo` is the cause of the problem you encountered.  Try this instead:

    project$ mv ../hugo/hugo .
    project$ hugo

In Hugo v0.12 and earlier versions, there was a bug that if you were to prepend the path to the `hugo` executable, like `../hugo/` in your `../hugo/hugo`, Hugo would actually try to look for the website config file not in your current directory, but in the path of the Hugo executable, i.e. `../hugo/config.{toml|yaml|json}`.  See "Pull Request #663: Use current working dir as WorkingDir instead of hugo executable's dir" for the whole story.

The issue has been fixed by @tatsushid and merged by @spf13 as 1091702 on December 11, 2014.  I recommend that you upgrade to the latest v0.13-DEV version, and your `../hugo/hugo` command would work as intended without patching Viper.

If you intend to stay with Hugo v0.12 for the time being, I recommend that you move the `hugo` executable to a path specified by the `PATH` environment variable, say `/usr/local/bin`.

Note to self: Add a note about this to the Hugo documentation before I go to bed tonight.  :-)

I am closing this issue because I considered it fixed by PR #663.  If there is any problem, feel free to comment and reopen this issue.

Cheers,
Anthony

**Closed by anthonyfok** 2015-01-18 04:04 UTC

**Comment by justin-calleja** [comment] 2015-01-18 16:15
Hi @anthonyfok  (giving in and using Github conventions from now on),

I've tried it out with the current master as I could not find branch/tag v0.13-DEV. But 1091702 is in current master.

It's working fine - thanks! 

Cheers,
Justin

**Comment by anthonyfok** [comment] 2015-01-18 20:14
Hi @justin-calleja,

Thanks!  I am so glad it is working for you!  :-)

I am sorry I was ambiguous.  The v0.13-DEV is the version number I got from running `hugo version`, and you are right: there is no such branch or tag in the repository, though I suppose there will be a `v0.13.docs` branch in the future when v0.13 is released.  :-)

Cheers,
Anthony
