### ISSUE TITLE
macOS Sierra needs Go 1.7

### ISSUE THREAD

**Issue by thepian** [spf13/hugo#2338] opened 2016-08-07 18:35 UTC
I just tested Hugo with Sierra. I'm not sure what fails it is inconsistent.

20:27 $ hugo server --theme=flow-theme --buildDrafts
unexpected fault address 0x15e18b24be1a
fatal error: fault
[signal 0xb code=0x1 addr=0x15e18b24be1a pc=0x15e18b24be1a]

goroutine 1 [running]:
runtime.throw(0x86f7d0, 0x5)
	/usr/local/Cellar/go/1.6.3/libexec/src/runtime/panic.go:547 +0x90 fp=0xc8200fe6b8 sp=0xc8200fe6a0
runtime.sigpanic()
	/usr/local/Cellar/go/1.6.3/libexec/src/runtime/sigpanic_unix.go:27 +0x2ba fp=0xc8200fe708 sp=0xc8200fe6b8
github.com/spf13/fsync.(*Syncer).sync(0xc8200ff808, 0xc82025fcb0, 0x2b, 0xc82025fd40, 0x2b)
	/private/tmp/hugo-20160807-1945-16nmquj/hugo-0.16/src/github.com/spf13/fsync/fsync.go:159 +0x634 fp=0xc8200fea10 sp=0xc8200fe708
github.com/spf13/fsync.(*Syncer).sync(0xc8200ff808, 0xc820052240, 0x20, 0xc8200522e0, 0x20)
	/private/tmp/hugo-20160807-1945-16nmquj/hugo-0.16/src/github.com/spf13/fsync/fsync.go:185 +0xb44 fp=0xc8200fed18 sp=0xc8200fea10
github.com/spf13/fsync.(*Syncer).sync(0xc8200ff808, 0xc82024df20, 0x12, 0xc82024df60, 0x12)
	/private/tmp/hugo-20160807-1945-16nmquj/hugo-0.16/src/github.com/spf13/fsync/fsync.go:185 +0xb44 fp=0xc8200ff020 sp=0xc8200fed18
github.com/spf13/fsync.(*Syncer).sync(0xc8200ff808, 0xc8201f3300, 0xe, 0xc8201f33f0, 0xe)
	/private/tmp/hugo-20160807-1945-16nmquj/hugo-0.16/src/github.com/spf13/fsync/fsync.go:185 +0xb44 fp=0xc8200ff328 sp=0xc8200ff020
github.com/spf13/fsync.(*Syncer).sync(0xc8200ff808, 0x869528, 0x1, 0x869528, 0x1)
	/private/tmp/hugo-20160807-1945-16nmquj/hugo-0.16/src/github.com/spf13/fsync/fsync.go:185 +0xb44 fp=0xc8200ff630 sp=0xc8200ff328
github.com/spf13/fsync.(*Syncer).syncRecover(0xc8200ff808, 0x869528, 0x1, 0x869528, 0x1, 0x0, 0x0)
	/private/tmp/hugo-20160807-1945-16nmquj/hugo-0.16/src/github.com/spf13/fsync/fsync.go:116 +0x8c fp=0xc8200ff660 sp=0xc8200ff630
github.com/spf13/fsync.(*Syncer).Sync(0xc8200ff808, 0x869528, 0x1, 0x869528, 0x1, 0x0, 0x0)
	/private/tmp/hugo-20160807-1945-16nmquj/hugo-0.16/src/github.com/spf13/fsync/fsync.go:91 +0x17d fp=0xc8200ff6d8 sp=0xc8200ff660
github.com/spf13/hugo/commands.copyStatic(0x0, 0x0)
	/private/tmp/hugo-20160807-1945-16nmquj/hugo-0.16/src/github.com/spf13/hugo/commands/hugo.go:613 +0x6c8 fp=0xc8200ff838 sp=0xc8200ff6d8
github.com/spf13/hugo/commands.build(0xc8200ff9be, 0x1, 0x1, 0x0, 0x0)
	/private/tmp/hugo-20160807-1945-16nmquj/hugo-0.16/src/github.com/spf13/hugo/commands/hugo.go:518 +0x11e fp=0xc8200ff978 sp=0xc8200ff838
github.com/spf13/hugo/commands.server(0xc8ab80, 0xc82024d880, 0x0, 0x2, 0x0, 0x0)
	/private/tmp/hugo-20160807-1945-16nmquj/hugo-0.16/src/github.com/spf13/hugo/commands/server.go:163 +0x6f2 fp=0xc8200ffc60 sp=0xc8200ff978
github.com/spf13/cobra.(*Command).execute(0xc8ab80, 0xc82024d700, 0x2, 0x2, 0x0, 0x0)
	/private/tmp/hugo-20160807-1945-16nmquj/hugo-0.16/src/github.com/spf13/cobra/command.go:568 +0x668 fp=0xc8200ffd78 sp=0xc8200ffc60
github.com/spf13/cobra.(*Command).ExecuteC(0xc89420, 0xc8ab80, 0x0, 0x0)
	/private/tmp/hugo-20160807-1945-16nmquj/hugo-0.16/src/github.com/spf13/cobra/command.go:658 +0x55c fp=0xc8200ffe88 sp=0xc8200ffd78
github.com/spf13/hugo/commands.Execute()
	/private/tmp/hugo-20160807-1945-16nmquj/hugo-0.16/src/github.com/spf13/hugo/commands/hugo.go:168 +0x77 fp=0xc8200fff28 sp=0xc8200ffe88
main.main()
	/private/tmp/hugo-20160807-1945-16nmquj/hugo-0.16/main.go:26 +0x28 fp=0xc8200fff40 sp=0xc8200fff28
runtime.main()
	/usr/local/Cellar/go/1.6.3/libexec/src/runtime/proc.go:188 +0x2b0 fp=0xc8200fff90 sp=0xc8200fff40
runtime.goexit()
	/usr/local/Cellar/go/1.6.3/libexec/src/runtime/asm_amd64.s:1998 +0x1 fp=0xc8200fff98 sp=0xc8200fff90

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/local/Cellar/go/1.6.3/libexec/src/runtime/asm_amd64.s:1998 +0x1

goroutine 7 [select]:
github.com/spf13/viper.(*Viper).WatchConfig.func1.1(0xc8201f6240, 0xc8201f0ec0, 0x3a, 0xc8201041c0)
	/private/tmp/hugo-20160807-1945-16nmquj/hugo-0.16/src/github.com/spf13/viper/viper.go:246 +0x54e
created by github.com/spf13/viper.(*Viper).WatchConfig.func1
	/private/tmp/hugo-20160807-1945-16nmquj/hugo-0.16/src/github.com/spf13/viper/viper.go:262 +0x203

goroutine 6 [syscall]:
syscall.Syscall6(0x16b, 0x3, 0x0, 0x0, 0xc820274e70, 0xa, 0xcaf030, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.6.3/libexec/src/syscall/asm_darwin_amd64.s:41 +0x5
golang.org/x/sys/unix.kevent(0x3, 0x0, 0x0, 0xc820274e70, 0xa, 0xcaf030, 0x0, 0x0, 0x0)
	/private/tmp/hugo-20160807-1945-16nmquj/hugo-0.16/src/golang.org/x/sys/unix/zsyscall_darwin_amd64.go:207 +0x7f
golang.org/x/sys/unix.Kevent(0x3, 0x0, 0x0, 0x0, 0xc820274e70, 0xa, 0xa, 0xcaf030, 0x0, 0x0, ...)
	/private/tmp/hugo-20160807-1945-16nmquj/hugo-0.16/src/golang.org/x/sys/unix/syscall_bsd.go:448 +0x94
github.com/fsnotify/fsnotify.read(0x3, 0xc820274e70, 0xa, 0xa, 0xcaf030, 0x0, 0x0, 0x0, 0x0, 0x0)
	/private/tmp/hugo-20160807-1945-16nmquj/hugo-0.16/src/github.com/fsnotify/fsnotify/kqueue.go:493 +0x8d
github.com/fsnotify/fsnotify.(*Watcher).readEvents(0xc8201f6240)
	/private/tmp/hugo-20160807-1945-16nmquj/hugo-0.16/src/github.com/fsnotify/fsnotify/kqueue.go:284 +0x193
created by github.com/fsnotify/fsnotify.NewWatcher
	/private/tmp/hugo-20160807-1945-16nmquj/hugo-0.16/src/github.com/fsnotify/fsnotify/kqueue.go:62 +0x344

goroutine 19 [chan receive]:
github.com/spf13/viper.(*Viper).WatchConfig.func1(0xc8201041c0)
	/private/tmp/hugo-20160807-1945-16nmquj/hugo-0.16/src/github.com/spf13/viper/viper.go:265 +0x248
created by github.com/spf13/viper.(*Viper).WatchConfig
	/private/tmp/hugo-20160807-1945-16nmquj/hugo-0.16/src/github.com/spf13/viper/viper.go:266 +0x35

**Comment by thepian** [comment] 2016-08-07 18:56
I assume this is the cause:

https://github.com/golang/go/issues/16354

**Comment by bep** [comment] 2016-08-07 19:05
Fsnotify uses syscalls in https://godoc.org/golang.org/x/sys/unix -- and although it may be related, I assume it will not be fixed in the same patch(es).

**Comment by bep** [comment] 2016-08-07 21:54
@thepian could you test this with the latest Go (1.7 RC?)?

**Comment by nathany** [comment] 2016-08-08 00:42
Could it be related to https://github.com/golang/go/issues/16579? Best to test with Go 1.7 RC5 or better.

**Comment by brasilikum** [comment] 2016-08-10 07:46
I am on the latest MacOS Sierra. Before go1.7 RC5 all my go programs broke like the one above. 

Now I am on go1.7rc5. I can confirm that hugo v0.16 works without issues.

**Comment by bep** [comment] 2016-08-10 07:51
@brasilikum that is good to know. But that means that we will have to do a release before Sierra. I'll keep this open to track that.

**Comment by brasilikum** [comment] 2016-08-10 08:32
Still working on go1.7 RC6

**Comment by nathany** [comment] 2016-08-10 16:20
If all goes well, Go 1.7 should be released on Monday, August 15th.

@bep Could v0.16 just be re-released with binaries compiled with Go 1.7?

**Comment by bep** [comment] 2016-08-10 17:49
@nathany not easy (no vendoring) ... and we do have some important bug fixes since 0.16.

**Comment by nathany** [comment] 2016-08-10 18:34
ahh, okay.

**Comment by brasilikum** [comment] 2016-08-16 09:06
[https://blog.golang.org/go1.7](Go 1.7 is released)

**Comment by AbeEstrada** [comment] 2016-09-26 22:26
After a clean macOS Sierra install, I tried to install `hugo` from `brew` it fails because of this issue.

**Comment by moorereason** [comment] 2016-09-26 22:29
@AbeEstrada,

Yes, we know.  That's why this issue is still open.

https://discuss.gohugo.io/t/hugo-crashes-on-macos-sierra/4101/13

**Closed** 2016-10-18 16:55 UTC
