### ISSUE TITLE
Can't use HTML comments anymore in Markdown files

### ISSUE THREAD

**Issue by yacoob** [spf13/hugo#1080] opened 2015-04-27 08:31 UTC
In `0.12`, you could use:
```markdown
<!--- foo -->
```
to insert comments into your content files. With `0.13`, this no longer works. If you put a line like this in middle of a paragraph, it gets converted to normal text:

```markdown
blahblah
<!--- foo -->
rhubarb
```

becomes

```html
blahblah
-&lt;!&ndash; foo &ndash;&gt;
rhubarb
```

If you separate comment in the source file by extra empty lines, the conversion is inhibited *but* extra <p> are added:

```markdown
blahblah
<!--- foo -->
rhubarb
```

becomes

```html
blahblah
</p>
<!-- foo -->
<p>
rhubarb
```

This is annoying :(

**Comment by bep** [comment] 2015-04-29 11:26
Please add an issue at https://github.com/russross/blackfriday

**Comment by bep** [comment] 2015-04-29 11:44
This is a duplicate of #729

**Closed by bep** 2015-04-29 11:44 UTC

**Comment by bep** [comment] 2015-10-11 09:20
@yacoob this should be now fixed in Blackfriday; is this something you could verify (needs a fresh Hugo build).
