### ISSUE TITLE
0.20.2 Exception with Raspberry Pi B

### ISSUE THREAD

**Issue by frenchja** [spf13/hugo#3379] opened 2017-04-24 00:41 UTC
# Setup

```
uname -a
Linux raspberrypi 4.9.23+ #989 Wed Apr 19 15:19:10 BST 2017 armv6l GNU/Linux

lsb_release -a
No LSB modules are available.
Distributor ID: Raspbian
Description:    Raspbian GNU/Linux 8.0 (jessie)
Release:        8.0
Codename:       jessie

go version
go version go1.3.3 linux/arm

type -P hugo
/usr/bin/hugo
```

# Behavior
```bash
hugo new site .
Illegal instruction
```

Occurs with:

- 0.20.2
- 0.19
- 0.17

Does not occur with:
- 0.16-1

**Comment by bep** [comment] 2017-04-24 07:16
Duplicate of https://github.com/spf13/hugo/issues/3176

Not sure if that helps you, either, but I'm closing this now, either way. We now about this, and we may fix it also in the GitHub builds at some point.

**Closed by bep** 2017-04-24 07:16 UTC
