### ISSUE TITLE
panic (mkdir: file exists)

### ISSUE THREAD

**Issue by moshee** [spf13/hugo#2983] opened 2017-01-23 05:59 UTC
```
$ hugo version
Hugo Static Site Generator v0.18.1 BuildDate: 2016-12-30T02:02:43-08:00
```

What I did: created a content dir `content/complete` after creating a layout template `layouts/section/complete.html` with `hugo -w` running

Expected: Hugo renders `complete` content (currently empty) into `public/complete/`

Got: Hugo created an empty **file** `public/complete` after adding the empty dir, and did this upon auto-render after putting something in it:

```
2017/01/22 21:50:03 mkdir /home/tsp/tsp/public/complete/: file exists
panic: mkdir /home/tsp/tsp/public/complete/: file exists


goroutine 195 [running]:
panic(0xa19600, 0xc420394e00)
        /usr/local/Cellar/go/1.7.4/libexec/src/runtime/panic.go:500 +0x1a1
log.Panicln(0xc4202bbaa0, 0x1, 0x1)
        /usr/local/Cellar/go/1.7.4/libexec/src/log/log.go:334 +0xc9
github.com/spf13/hugo/vendor/github.com/spf13/afero.WriteReader(0xdfca20, 0xe54d70, 0xc420344330, 0x28, 0xdf0ba0, 0xc4201c61c0, 0xdf25a0, 0xc420344390)
        /Users/bep/go/src/github.com/spf13/hugo/vendor/github.com/spf13/afero/util.go:49 +0x272
github.com/spf13/hugo/helpers.WriteToDisk(0xc420344330, 0x28, 0xdf0ba0, 0xc4201c61c0, 0xdfca20, 0xe54d70, 0x0, 0xc42000e120)
        /Users/bep/go/src/github.com/spf13/hugo/helpers/path.go:585 +0x5d
github.com/spf13/hugo/target.(*PagePub).Publish(0xc420321080, 0xc42047c340, 0x8, 0xdf0ba0, 0xc4201c61c0, 0x0, 0x0)
        /Users/bep/go/src/github.com/spf13/hugo/target/page.go:47 +0x96
github.com/spf13/hugo/hugolib.(*Site).writeDestPage(0xc4201c8500, 0xc42047c340, 0x8, 0x7fe1f4525068, 0xc420321080, 0xdf0ba0, 0xc4201c61c0, 0x0, 0x0)
        /Users/bep/go/src/github.com/spf13/hugo/hugolib/site.go:1929 +0x15f
github.com/spf13/hugo/hugolib.(*Site).renderAndWritePage(0xc4201c8500, 0xae4884, 0x5, 0xc42047c340, 0x8, 0xae01a0, 0xc42051ed80, 0xc420322410, 0x5, 0x5, ...)
        /Users/bep/go/src/github.com/spf13/hugo/hugolib/site.go:1809 +0x8b2
github.com/spf13/hugo/hugolib.pageRenderer(0xc4201c8500, 0xc420442cc0, 0xc420442c60, 0xc4204be350)
        /Users/bep/go/src/github.com/spf13/hugo/hugolib/site_render.go:73 +0x3de
created by github.com/spf13/hugo/hugolib.(*Site).renderPages
        /Users/bep/go/src/github.com/spf13/hugo/hugolib/site_render.go:46 +0x163
```

**Comment by xhesh** [comment] 2017-03-23 17:56
@moshee hi, i'll look into this issue. couple of questions.
1) which version of hugo are you using? if you're up to date, is this still an issue?
2) when you say that you created a content directory, did you do that with hugo new command or in some other way?

**Comment by moshee** [comment] 2017-05-08 13:47
Sorry for neglecting this issue. I somehow did not see your reply or made a note to get around to it but never did.

Anyways, this still happens on 0.20.7. I will try to get a minimal failing site example ready today. To answer your questions,

1. 0.20.7 release
2. I used `mkdir`.

The current panic is:

```
Started building sites ...
2017/05/08 06:37:46 mkdir /home/tsp/tsp/public/staff/: file exists
panic: mkdir /home/tsp/tsp/public/staff/: file exists

goroutine 72 [running]:
log.Panicln(0xc42024f8a8, 0x1, 0x1)
        /usr/local/go/src/log/log.go:336 +0xc0
github.com/spf13/hugo/vendor/github.com/spf13/afero.WriteReader(0xec49c0, 0xf2c180, 0xc4202f9a10, 0x24, 0xeb7de0, 0xc42008cc40, 0xeb96e0, 0xc4202f9a70)
        /Users/bep/go/src/github.com/spf13/hugo/vendor/github.com/spf13/afero/util.go:49 +0x25b
github.com/spf13/hugo/helpers.WriteToDisk(0xc4202f9a10, 0x24, 0xeb7de0, 0xc42008cc40, 0xec49c0, 0xf2c180, 0xc4202f9980, 0xc42008caf0)
        /Users/bep/go/src/github.com/spf13/hugo/helpers/path.go:570 +0x5d
github.com/spf13/hugo/hugolib.(*Site).publish(0xc4201a4900, 0xc420318440, 0x10, 0xeb7de0, 0xc42008cc40, 0xc42028cdc0,
0x13)
        /Users/bep/go/src/github.com/spf13/hugo/hugolib/site.go:2009 +0xf2
github.com/spf13/hugo/hugolib.(*Site).renderAndWriteXML(0xc4201a4900, 0xc420465aca, 0x6, 0xc420318440, 0x10, 0xb6e4c0, 0xc4202e34a0, 0xc42005a380, 0x7, 0x8, ...)
        /Users/bep/go/src/github.com/spf13/hugo/hugolib/site.go:1916 +0x552
github.com/spf13/hugo/hugolib.(*Site).renderRSS(0xc4201a4900, 0xc4202e34a0, 0xc42005a380, 0x7)
        /Users/bep/go/src/github.com/spf13/hugo/hugolib/site_render.go:230 +0x3c7
github.com/spf13/hugo/hugolib.pageRenderer(0xc4201a4900, 0xc4204b2660, 0xc4204b2600, 0xc4201e9690)
        /Users/bep/go/src/github.com/spf13/hugo/hugolib/site_render.go:104 +0x8fd
created by github.com/spf13/hugo/hugolib.(*Site).renderPages
        /Users/bep/go/src/github.com/spf13/hugo/hugolib/site_render.go:45 +0x156
Started building sites ...
2017/05/08 06:37:51 mkdir /home/tsp/tsp/public/staff/: file exists
panic: mkdir /home/tsp/tsp/public/staff/: file exists

...a whole bunch of other goroutines...
```

**Comment by moorereason** [comment] 2017-05-09 21:03
@moshee,
I'm unable to reproduce this error.  Can you start from scratch and show step by step how to reproduce?

**Comment by moshee** [comment] 2017-05-09 23:27
It only appears to happen with `hugo -w`. Here is an exact list of steps I can use to reproduce the issue:

```
moshee@deimos(~/downloads) ⚡ hugo version
Hugo Static Site Generator v0.20.7 linux/amd64 BuildDate: 2017-05-03T00:39:25-07:00
moshee@deimos(~/downloads) ⚡ hugo new site test
Congratulations! Your new Hugo site is created in /home/moshee/downloads/test.

Just a few more steps and you're ready to go:

1. Download a theme into the same-named folder.
   Choose a theme from https://themes.gohugo.io/, or
   create your own with the "hugo new theme <THEMENAME>" command.
2. Perhaps you want to add some content. You can add single files
   with "hugo new <SECTIONNAME>/<FILENAME>.<FORMAT>".
3. Start the built-in live server via "hugo server".

Visit https://gohugo.io/ for quickstart guide and full documentation.
moshee@deimos(~/downloads) ⚡ cd test
moshee@deimos(~/downloads/test) ⚡ # started hugo -w in a new terminal

--- hugo -w output in other terminal: ---
Started building sites ...
Built site for language en:
0 draft content
0 future content
0 expired content
0 regular pages created
6 other pages created
0 non-page files copied
0 paginator pages created
0 categories created
0 tags created
total in 2 ms
Watching for changes in /home/moshee/downloads/test/content
Press Ctrl+C to stop
adding created directory to watchlist /home/moshee/downloads/test/content/test
--- end ---

moshee@deimos(~/downloads/test) ⚡ mkdir content/test

---
Change detected, rebuilding site
2017-05-09 16:24 -0700
Source changed /home/moshee/downloads/test/content/test
ERROR 2017/05/09 16:24:12 Errors rendering pages: read /home/moshee/downloads/test/content/test: is a directory
Built site for language en:
0 draft content
0 future content
0 expired content
0 regular pages created
6 other pages created
1 non-page files copied
0 paginator pages created
0 tags created
0 categories created
total in 2 ms
---

moshee@deimos(~/downloads/test) ⚡ touch content/test/test.md

---
Change detected, rebuilding site
2017-05-09 16:24 -0700
Source changed /home/moshee/downloads/test/content/test/test.md
2017/05/09 16:24:24 mkdir /home/moshee/downloads/test/public/test/: file exists
panic: mkdir /home/moshee/downloads/test/public/test/: file exists


goroutine 62 [running]:
log.Panicln(0xc42030b8a8, 0x1, 0x1)
        /usr/local/go/src/log/log.go:336 +0xc0
github.com/spf13/hugo/vendor/github.com/spf13/afero.WriteReader(0xec49c0, 0xf2c180, 0xc420478880, 0x31, 0xeb7de0, 0xc4200aa620, 0xeb96e0, 0xc420477440)
        /Users/bep/go/src/github.com/spf13/hugo/vendor/github.com/spf13/afero/util.go:49 +0x25b
github.com/spf13/hugo/helpers.WriteToDisk(0xc420478880, 0x31, 0xeb7de0, 0xc4200aa620, 0xec49c0, 0xf2c180, 0xc420477320, 0xc4200aa5b0)
        /Users/bep/go/src/github.com/spf13/hugo/helpers/path.go:570 +0x5d
github.com/spf13/hugo/hugolib.(*Site).publish(0xc4201b2000, 0xc42047a560, 0xf, 0xeb7de0, 0xc4200aa620, 0xc42047b160, 0x13)
        /Users/bep/go/src/github.com/spf13/hugo/hugolib/site.go:2009 +0xf2
github.com/spf13/hugo/hugolib.(*Site).renderAndWriteXML(0xc4201b2000, 0xc4204499c0, 0x5, 0xc42047a560, 0xf, 0xb6e4c0, 0xc420171860, 0xc42034da00, 0x7, 0x8, ...)
        /Users/bep/go/src/github.com/spf13/hugo/hugolib/site.go:1916 +0x552
github.com/spf13/hugo/hugolib.(*Site).renderRSS(0xc4201b2000, 0xc420171860, 0xc42034da00, 0x7)
        /Users/bep/go/src/github.com/spf13/hugo/hugolib/site_render.go:230 +0x3c7
github.com/spf13/hugo/hugolib.pageRenderer(0xc4201b2000, 0xc420055680, 0xc420055620, 0xc420347030)
        /Users/bep/go/src/github.com/spf13/hugo/hugolib/site_render.go:104 +0x8fd
created by github.com/spf13/hugo/hugolib.(*Site).renderPages
        /Users/bep/go/src/github.com/spf13/hugo/hugolib/site_render.go:45 +0x156
---

moshee@deimos(~/downloads/test) ⚡
```

**Comment by moorereason** [comment] 2017-05-10 00:36
@moshee, thanks for the clarification.  I can in fact reproduce this with v0.20.7, but it appears to be fixed in the latest dev branch (which I was testing with earlier).

Closing this issue since it seems like a rare case.  The fix will be in the next minor release.

**Closed by moorereason** 2017-05-10 00:36 UTC
Labels: Bug
