### ISSUE TITLE
Archetypes not working from theme

### ISSUE THREAD

**Issue by isaaki** [spf13/hugo#533] opened 2014-09-30 18:16 UTC
Archetypes are working from my project root, but not from themes. 

For getting them to work from my project root I had to add empty line returns (similar to the workaround here: https://github.com/spf13/hugo/issues/359). 

Ideas?

**Comment by tatsushid** [comment] 2015-01-10 21:07
If it's caused by the same reason of #359, it's also the same with #776

**Comment by bjornerik** [comment] 2015-01-19 08:09
Should be fixed by #785

**Closed by bjornerik** 2015-01-19 08:09 UTC
Labels: bug

**Comment by Asday** [comment] 2017-03-10 15:42
I still have the issue on hugo 0.19 and `master`.  I've created a repository [here](https://github.com/Asday/hugo-theme-archetype-issue).

**Comment by kva1966** [comment] 2017-03-14 04:25
Me too, I'm compiling from source via go get.

**Comment by Asday** [comment] 2017-04-11 09:45
Fixed in 0.20, this issue can now be clos...  Oh.
