### ISSUE TITLE
RawContent isn't raw anymore

### ISSUE THREAD

**Issue by bep** [spf13/hugo#2601] opened 2016-10-18 06:49 UTC
https://discuss.gohugo.io/t/rawcontent-not-working-in-0-17/4343

**Comment by joonazan** [comment] 2016-10-24 14:30
I am currently working on this. Have already reproduced the bug.

**Comment by joonazan** [comment] 2016-10-24 15:47
The problem is that Page.rawContent does not contain the raw content of the file. A comment states that this is to "save memory". This makes no sense, as clearly the raw content is needed.

rawContent and rawContentCopy should probably be named differently.

rawContentCopy should be eliminated altogether, because it serves no real purpose. Instead one could just not reassign rawContent. At least it should not be part of the struct, as it is only used in preparePagesForRender and the methods it calls.

I am going to do this refactoring of rawContentCopy, but what do you think I should do to rawContent?

**Comment by bep** [comment] 2016-10-24 15:59
>I am going to do this refactoring of rawContentCopy, but what do you think I should do to rawContent?

I would be surprised if `rawContentCopy` isn't needed. The current modification of the content saves one copy of the entire page sets, which makes a lot of sense if you have 10000 pages. 

I think we should let this one sit for a little bit. One option is to deprecate the `RawContent` method. It was probably exported a little bit hasty, and now it is time to think about it before too many start to depend on it.

**Comment by joonazan** [comment] 2016-10-25 16:01
I have made a pull request that removes Page.rawContentCopy. #2634 

It was only used in on method and functions that that method calls, that really should be more obviously part of the method.

**Comment by joonazan** [comment] 2016-10-25 16:06
I don't think the memory savings of not having the raw content are worth it. It is meant to be written by hand after all, which means you need pretty many writers to just keep up with RAM growth.

**Comment by bep** [comment] 2016-10-25 16:35
>It is meant to be written by hand after all,

What do you mean?

**Comment by bep** [comment] 2016-10-25 17:06
As to numbers: https://github.com/bep/hugo-benchmark can be useful.

**Comment by joonazan** [comment] 2016-10-25 17:26
>> It is meant to be written by hand after all,
> What do you mean?

I meant that the raw content is not automatically generated and is therefore rather limited in size.

I do not have any data on whether raw content is needed other than that there is a person who had this issue with it. Leaving out the feature can be a good idea IMO, but not because of memory optimization. Less features is a desirable goal.

Why not optimize memory? A book is about a megabyte long. For the raw content to take up a gigabyte, it'd have to be about 1k books. Sites with a lot of text are usually one book long. [For example Fallen London has stated that it is 1.5M words long](http://www.failbettergames.com/why-is-fallen-london-still-free-to-play/). Which is only a few megabytes.

The only kind of site I can think of where memory would be even significant, though not problematic is the site of a large news producer. And for that amount of content you'd want so much traffic that I don't think you'd care about wasting a gigabyte of memory.

**Comment by aphecetche** [comment] 2016-10-31 20:38
If I may add my 2 cents, this "RawContent-not-being-raw-anymore" issue is breaking the ability to integrate with (at least) reveal.js for instance (see https://discuss.gohugo.io/t/integration-with-reveal-js-to-present-slides/3047), which I find highly annoying ;-)

**Comment by moorereason** [comment] 2016-12-01 03:30
An alternative approach:  allow the use of `markup = raw` in the content front-matter which will bypass the  markup renderers.  Then just use `.Content` in the templates.

**Comment by bep** [comment] 2016-12-01 08:53
>An alternative approach: allow the use of markup = raw 

Yes, that I can like. I will first do a quick check to see what performance impact creating a copy of the content has.

**Closed** 2016-12-01 16:29 UTC
Labels: kind/bug
