### ISSUE TITLE
TOC links not working

### ISSUE THREAD

**Issue by RickCogley** [spf13/hugo#1138] opened 2015-05-13 10:08 UTC
Hello - please see http://discuss.gohugo.io/t/toc-links-incorrect/1182 .

TOC links are not honoring the page's permalink, and simply jump back to the home page. 

Some salient info: 
* canonifyurls - false (not set in config.toml, so the default)
* baseurl - http://www.mysite.com (no trailing slash)
* hugo version - v0.14-DEV BuildDate: 2015-05-13T11:41:02+09:00

**Comment by RickCogley** [comment] 2015-05-13 10:19
I changed canonifyurls to true, restarted hugo server, and no change. FYI

**Comment by bep** [comment] 2015-05-13 10:29
Thinking and looking at this -- ToC links are on the form `a href="#some-id"`

* Are you seeing something different in your generated source?
* Do you happen to have a base href tag set?

**Comment by RickCogley** [comment] 2015-05-13 10:45
Hi - yes, I have it in my header partial template. 

      <base href="{{ .Site.BaseUrl }}">

Reading about it, strictly speaking it seems you're supposed to add a trailing slash at the end of a base href tag.

**Comment by RickCogley** [comment] 2015-05-13 10:52
Adding one does not seem to make a difference for this specific problem.

**Comment by bep** [comment] 2015-05-13 12:52
OK, then this is a duplicate of #811

**Closed by bep** 2015-05-13 12:52 UTC

**Comment by RickCogley** [comment] 2015-05-13 14:33
I mean, adding a slash. 

Anyway, removed the base tag, and all is well. TOC works.
