### ISSUE TITLE
hugo server hangs in raspberry pi

### ISSUE THREAD

**Issue by xuqingfeng** [spf13/hugo#1716] opened 2015-12-18 01:39 UTC
I'm setting up hugo in a raspberry pi (armV7), when I run `hugo server -v`, it hangs until I exit it with `Ctrl + C`.

here is the output:

```
INFO: 2015/12/18 Using config file: /home/xqf/pi-hugo/config.toml
INFO: 2015/12/18 syncing from /home/xqf/pi-hugo/themes/cactus/static to /

```

**Comment by moorereason** [comment] 2015-12-18 03:36
This is a known issue with Hugo 0.15.  See [forum discussion](https://discuss.gohugo.io/t/hugo-server-returns-runtime-error-on-armhf/2293).  It's been fixed in 0.16-DEV.

The work around is to run ``hugo server --renderToDisk``.  The problem is with the new "render to memory" feature that's enabled by default when running in server mode.

@anthonyfok,
can you add a **Known Issues** section to the 0.15 release notes about this issue affecting Win32 and ARM?  Should probably say the same thing or link to the release notes from the Github releases page.

**Comment by anthonyfok** [comment] 2015-12-19 07:25
> @anthonyfok,
can you add a Known Issues section to the 0.15 release notes about this issue affecting Win32 and ARM? Should probably say the same thing or link to the release notes from the Github releases page.

@moorereason, thank you for the heads-up!  I will do this before I go to bed tonight.

**Comment by anthonyfok** [comment] 2015-12-19 10:52
> about this issue affecting Win32

Actually, if I am not mistaken, this issue affects Win64 users running a Win32 (so-called "windows_386") binary.  Running hugo_0.15_windows_386.exe on Win32 should work just fine.

**Comment by anthonyfok** [comment] 2015-12-19 11:26
Sorry, I take back what I just said.  The Win32 binary would crash anywhere due to this "bug" in Go that you found earlier: https://golang.org/pkg/sync/atomic/#pkg-note-BUG

**Closed** 2015-12-19 11:34 UTC
Labels: kind/docs

**Comment by anthonyfok** [comment] 2015-12-19 11:38
The suggested "Known Issues" section has been added to the end of the v0.15 Release Notes, see:

* http://gohugo.io/meta/release-notes/#known-issues:066aa012c0230cd32faa0776e0a81250
* https://github.com/spf13/hugo/releases/tag/v0.15

**Comment by moorereason** [comment] 2015-12-19 14:18
Looks good, @anthonyfok

**Comment by matthewp** [comment] 2016-01-08 19:47
On my raspberry pi I get "Illegal instruction" when I run Hugo. No such problem on 0.14.

**Comment by anthonyfok** [comment] 2016-06-13 13:38
The newly release Hugo v0.16 works great on my Raspberry Pi 1 (Model B Revision 1.0 + ECN0001) and Raspberry Pi 3.  It can be downloaded from:

* https://github.com/spf13/hugo/releases/download/v0.16/hugo_0.16-1_armhf.deb
* https://packages.debian.org/sid/armhf/hugo/download
