### ISSUE TITLE
File permissions in /public

### ISSUE THREAD

**Issue by rmorriso** [spf13/hugo#130] opened 2013-11-21 17:41 UTC
When content is generated to /public, directories are created with permission 0764. This works fine when running in server mode (same user that generates the file is running the server). But if hugo is being used by one user to generate content that will be served by another user (e.g. Apache), the permissions aren't correct. 

Use permissions 0755 instead in target/file.go:
...
func writeToDisk(translated string, r io.Reader) (err error) {
        path, _ := filepath.Split(translated)
        ospath := filepath.FromSlash(path)

        if ospath != "" {
                err = os.MkdirAll(ospath, 0755) // rwx, rx rx
                if err != nil {
                        panic(err)
                }
        }
...

**Comment by synful** [comment] 2015-01-04 22:06
I think that panicking is the wrong behavior here. I just tried to run `hugo -d /nonexistant/directory`, and it panicked with `mkdir /nonexistant: permission denied`. Is there a way that this could be returned as an error and reported cleanly at the top level?

**Comment by anthonyfok** [comment] 2015-01-25 11:45
It is interesting I never noticed this as a problem before: Despite the apparent `0777` permission for the MkdirAll() calls, Hugo creates 0755 directories and 0644 files on my computer, and that is perfectly fine with me.

It turns out that, at least on Linux, the permission bits go through the ***file mode creation mask***, or the ***umask***, which defaults to 0022, which subtracts from the 0777 (dirs) and 0666 (files) permission bits, resulting in the sane 0755 and 0644 permissions.

According to [this Apple article: "Mac OS X: Setting a custom umask"](http://support.apple.com/en-ca/HT201684), the default umask is also 0022, so it should be the same as on Linux and other UNIX variants.

For those who prefer 0775 or 0770, perhaps the best way is to run `umask 0002` or `umask 0007` manually before running `hugo`?

**Comment by anthonyfok** [comment] 2015-01-25 11:55
@synful, thank you for your report!  I can reproduce the panic you saw, when `hugo -d /nonexistant/directory` is run in a directory containing a `content/` subdirectory, no matter it is empty or not.

In order to better track this bug that you have found, and to give proper credit to your discovery, could you please create a new issue on this panic bug?  Many thanks!

**Comment by synful** [comment] 2015-01-25 20:25
OK, added as [issue 837](https://github.com/spf13/hugo/issues/837).

**Comment by rmorriso** [comment] 2015-01-26 08:36
Hi folks,
Just a comment on some of the discussion relating to file permissions. World writeable directories (0700) and files (0666) should be avoided. They reduce security and expose their contents to accidental deletion by absolutely anyone logged into the host. In the case of hugo running in “build mode", the target directory should be owned by the user that runs hugo and the files and directories should be 0644 and 0755 respectively. This will allow a web servers like Apache or Nginx to read/serve the generated content. If hugo is running in "server mode” this is less important since the owner of the hugo process presumably has read/write access to the hugo content.
- Rick

**Comment by anthonyfok** [comment] 2015-01-26 10:40
Hi @rmorriso,

Thank you for your comment.

I fully agree with what you say about security, and indeed I would never use world-writable/readable permissions like 0777 or 0666 for any of my files.

That said, Hugo (and the underlying Go functions) fully respects your `umask` settings, and OSes are supposed to have sane defaults like 022 or 002, so by default, e.g. on Mac OS X, GNU/Linux, etc.

So, despite how codes like `err = os.MkdirAll(ospath, 0777)` appearing to be dangerous on the surface, it is actually very safe because that `0777` gets masked by the umask, so roughly, `0777 - 0022` becomes `0755`, and `0666 - 0022` gives 0644, a very safe and reasonable default.

Now, if an end user were to do crazy things like setting his/her umask to 000... well, then all directories and files are created as 0777 and 0666, not just Hugo files.

So, I think the current version of Hugo is already doing the right thing by fully respecting the system umask, giving the sane defaults of 0755 and 0644 on our supported operating systems.  So, it is time to close this bug report?  :-)

**Comment by rmorriso** [comment] 2015-01-26 11:26
Hi @spf13,
On the Linux hosts I work on the default umask is 022 (see man pam_umask on Ubuntu, for example). And, certainly, if you create a file or directory in a login shell you get files with permissions 0755 and 0644 as you describe. 

When I run hugo, however, the permissions under the public directory are 0775 and 0664 respectively. If I change my umask either in my own shell or in /etc/login.defs it has no effect on the file permissions hugo sets on the contents of public. If the objective is for hugo to respect umask then I think it still isn’t quite working.
- Rick

**Comment by tatsushid** [comment] 2015-01-26 12:02
I tried some tests with umask and got result if I changed umask from 022 to 002, the newly created directory and files correctly had 775 and 664 but the directory and files came from `static` and theme's `static` directory were assigned those original permissions. I guess it's the situation @rmorriso mentioned in the last post and if so, we should consider what hugo should do. In my opinion, it's convenient hugo cares the situation especially copying theme's `static`

**Comment by anthonyfok** [comment] 2015-01-26 12:05
@tatsushid  :+1:

**Comment by rmorriso** [comment] 2015-01-26 12:13
Ah. OK. So the desired behaviour is that all files copied from static retain their existing permissions, while any new files or directories created by hugo receive the default umask?

This sounds reasonable.

**Comment by anthonyfok** [comment] 2015-01-26 12:20
Hi @rmorriso:

I think @tatsushid's answer has hit the nail on the head, i.e. probably the 0775 and 0664 files you saw came from the original permissions of the files in your `static/` directory, which Hugo copies to `public/` preserving the permissions.

That said, how you ended up with 0775 as the permission of your static directory is worthy of an investigation.  I suspect the following:

 1. Different umask settings between your: a. login shells, and b. non-login shells
 2. 

----

Are you running `hugo` non-interactively, as in a `hugo` deploy run triggered by a `git push`?  If so, I highly suspect that you are seeing the effect of "umask 002", which of course Hugo (and the underlying Go standard functions) obey, producing 0775 and 0664, which may be the default on your system for non-login shells.

It may also have to do with this [Ubuntu Blueprint: Change the default umask to 0002](https://blueprints.launchpad.net/ubuntu/+spec/umask-to-0002).  Related links:

  * https://bugs.debian.org/583971 — Debian Bug report logs - #583971
login.defs: UMASK 022 (and have pam_umask relax it to 002 for private usergroups)

  * /etc/logins.def:

        # If USERGROUPS_ENAB is set to "yes", that will modify this UMASK default value
        # for private user groups, i. e. the uid is the same as gid, and username is
        # the same as the primary group name: for these, the user permissions will be
        # used as group permissions, e. g. 022 will become 002.

That may be the reason that I am seeing my directories in my Ubuntu /home/foka directory having a mix of 0775 and 0755, either because of the default change, or that the system default became 002 for a non-root user like me (uid == gid == 1000; username == primary group name == foka), but perhaps I have added a "umask 022" in my `~/.profile`.

Whatever the reason, it can get confusing, and my head is spinning now.  :-)

**Comment by anthonyfok** [comment] 2015-01-26 12:23
@tatsushid: You have brought up a great point there.  Should Hugo copy the `static/` directory to `public/` exactly as is?  Or should it do some check and sanitizes unsafe permissions e.g. 0666 to 0644, while keeping already restrictive permissions intact?  E.g. 0400 → 0400 unchanged?  Something worthy of discussion indeed.

**Comment by rmorriso** [comment] 2015-01-26 12:29
I’m not using any Git hook. Simply running hugo command. My umask is 022. 

The results I was reporting were those obtained when running hugo inside the hugo/examples/blog directory. In that directory, the permissions on the contents of static are 0775 and 0664 (after doing a go get github.com/spf/hugo <http://github.com/spf/hugo>). So the permissions of static contents are being preserved as @tatsushid <https://github.com/tatsushid> described. This behavior seems ok to me.

**Comment by rmorriso** [comment] 2015-01-26 12:32
My feeling is to avoid designs that try to be “too smart.” I think if the hugo docs make it quite clear that permissions under static are preserved (SO BE CAREFUL) and that new files and directories are created with the default umask that should be fine…

**Comment by tatsushid** [comment] 2015-01-26 12:32
@anthonyfok, I think it is convenient but not required behavior and saw the similar situation at adding `notime` option i.e. https://github.com/spf13/hugo/pull/613 and around that. People would take care of their own `static` but not theme's `static` if they try to customized it by themselves.

**Comment by tatsushid** [comment] 2015-01-26 12:36
And we should think what it works on Windows. I now don't have the environment so I didn't test on it. Changes on the permission behavior doesn't affect hugo on Windows I guess but should confirm before making changes.

**Comment by anthonyfok** [comment] 2015-01-27 11:27
@tatsushid and @rmorriso, I agree with you.  I think it is quite okay to keep the current behaviour, as it is not a desirable behaviour for Hugo to be “too smart" or to second-guess the end users' intentions.

I think adding a note in the docs is a great idea.  @rmorriso, I have added your idea, to my TODO list, though Pull Requests are even more welcome!  :wink:

As this issue has already fixed in PR #146 by @droyo in December 2013, i.e. since Hugo v0.10, without further ado, I hereby close this issue.

**Closed by anthonyfok** 2015-01-27 11:27 UTC
Labels: bug
