### ISSUE TITLE
Support for Partial Rebuilds

### ISSUE THREAD

**Issue by rahul286** [spf13/hugo#406] opened 2014-08-14 19:37 UTC
First a big thank you to @spf13 for building fastest static site generators for big static sites. 

I have tried most of http://www.staticgen.com/ and many failed to build my site. 

Hugo builded 5000+ pages in 5 seconds. :+1: 

I am getting same performance for edits. If I edit something, it gets reflected very quickly, but I noticed entire site is rebuilt.

```
Change detected, rebuilding site

4762 pages created 
1535 tags created
8 categories created
in 5326 ms
Change detected, rebuilding site

4763 pages created 
1535 tags created
8 categories created
in 7385 ms
```

I am testing build performance with out of box theme. 

It may affect as theme customizations/shortcodes gets added. So in long distinct future, partial build support might be useful.

**Comment by digitalcraftsman** [comment] 2017-02-24 21:04
Isn't this a duplicate of #1643?

**Closed** 2017-02-24 21:11 UTC
Labels: Duplicate, Enhancement
