### ISSUE TITLE
build broken by dependency API change

### ISSUE THREAD

**Issue by jmhodges** [spf13/hugo#1345] opened 2015-08-10 01:36 UTC
The current hugo build is broken (if you have an old checkout lying around of russross/blackfriday) due to:

    # github.com/spf13/hugo/helpers
    helpers/content.go:78: undefined: blackfriday.EXTENSION_DEFINITION_LISTS
    helpers/content.go:182: undefined: blackfriday.EXTENSION_DEFINITION_LISTS

It's might be time for hugo to use godep to save its dependencies.

**Comment by bep** [comment] 2015-08-10 18:47
Duplicate of #1247

**Closed by bep** 2015-08-10 18:47 UTC

**Comment by bep** [comment] 2015-08-11 06:54
I was a little fast closing  this. This has been discussed before, and eventually we will have to bite the apple and get some dependency management, but not because of the api change above (a change we use) -- and maybe not before they get some kind of support in `go get` (1.6?)
