### ISSUE TITLE
Quick & useful: Configurable file extension

### ISSUE THREAD

**Issue by jesper-mortensen** [spf13/hugo#320] opened 2014-06-04 16:56 UTC
Quick but very useful feature request: Permit the user to configure a preferred file extension for generated HTML files, i.e. keep allow the user to specify `.htm` , `.aspx` , `.php` or any other file extension instead of `.html`

**Use cases:** Sites where content is well served by a static site generator, but which need a PHP contact us form / guest book / statistics package etc. On most hosts, the pages will only be parsed by the PHP interpreter if they have the right extension.

**Proposal:** Ideally, this could be a site-wide default setting, with a per-page override in the page frontmatter. I.e. a site config setting and page frontmatter setting called `extension`, with a default value of `html` .

**Comment by bep** [comment] 2015-07-25 21:16
@spf13 any updates on this?

**Comment by bep** [comment] 2015-10-09 20:53
@spf13 update?

**Comment by bep** [comment] 2015-11-18 23:00
@spf13 update?

**Comment by spf13** [comment] 2015-11-18 23:49
I'll review tomorrow or Friday. Working through the windows memory fs bug
now.

**Comment by bep** [comment] 2016-01-08 20:26
See 

https://discuss.gohugo.io/t/how-to-change-file-extension-for-homepage/2418

We have a `defaultExtension`. All page generation should use it.

**Comment by bep** [comment] 2017-02-28 19:11
This issue has been automatically marked as stale because it has not been commented on for at least four months.

The resources of the Hugo team are limited, and so we are asking for your help.

If this is a **bug** and you can still reproduce this error on the <code>master</code> branch, please reply with all of the information you have about it in order to keep the issue open.

If this is a **feature request**, and you feel that it is still valuable, please open a proposal at https://discuss.gohugo.io/.

This issue will automatically be closed in four months if no further activity occurs. Thank you for all your contributions.

**Comment by bep** [comment] 2017-03-01 09:23
**Note/Update:** This issue is marked as stale, and I may have said something earlier about "opening a thread on the discussion forum". Please don't.

If this is a **bug** and you can still reproduce this error on the latest <code>release</code> or the <code>master</code> branch, please reply with all of the information you have about it in order to keep the issue open.

If this is a **feature request**, and you feel that it is still relevant and valuable, please tell us why.

**Comment by bep** [comment] 2017-03-31 21:37
This will be fixed as part of #2828

**Closed** 2017-04-04 13:12 UTC
Labels: Bug, Keep
