### ISSUE TITLE
hugo server when BaseUrl has path does not serve any pages other than `/`

### ISSUE THREAD

**Issue by bguiz** [spf13/hugo#799] opened 2015-01-15 23:18 UTC
In `config.yaml`:

    baseurl: http://bguiz.github.io/js-standards

Then run command:

    rm -r public/* && hugo server --watch

Produces output:

	0 draft content 
	0 future content 
	10 pages created 
	23 tags created
	0 categories created
	in 217 ms
	Watching for changes in /code/js-standards/content
	Serving pages from /code/js-standards/public
	Web Server is available at http://localhost:1313/js-standards
	Press ctrl+c to stop

When visting the URL in browser: `http://localhost:1313/js-standards`,
this page (the root `index.html`) gets served, 
but all other expected URLs result in **HTTP 404 errors**.

Now making just one change in `config.yaml`:

    baseurl: http://bguiz.github.io

Then run command again:

    rm -r public/* && hugo server --watch

Produces output:

	0 draft content 
	0 future content 
	10 pages created 
	0 categories created
	23 tags created
	in 223 ms
	Watching for changes in /code/js-standards/content
	Serving pages from /code/js-standards/public
	Web Server is available at http://localhost:1313
	Press ctrl+c to stop

This leads me to conclude that the server command is broken,
for when the base URL contains a path after the domain name:

- `baseurl: http://bguiz.github.io` works
- `baseurl: http://bguiz.github.io/js-standards` **does not work**

**Comment by anthonyfok** [comment] 2015-01-16 00:21
Hello @bguiz,

Thank you for your bug report, though it is actually a duplicate of Issue #793: "`hugo server` not serving subdirectories".

We will be working on this issue soon.  But before a fix is committed, please try using:

    baseurl: http://bguiz.github.io/js-standards/

as a workaround.  Note the trailing slash at the very end of that string.  :-)

Personally, I am used to add a trailing slash (e.g. `http://bguiz.github.io/` and `http://bguiz.github.io/js-standards/`, except those ending e.g. `.html`, `.php`) to all my URLs, so I have been lucky and have never encountered this problem myself, until I noticed the lack of a trailing slash in Issue #793 which @trombonehero has kindly reported that I got to see the problem first-hand.

Cheers,
Anthony

**Closed** 2015-01-16 00:29 UTC
Labels: bug, duplicate
