### ISSUE TITLE
Tag ".net" creates invalid pagination

### ISSUE THREAD

**Issue by patrick-steele** [spf13/hugo#2110] opened 2016-04-27 01:05 UTC
I'm working on creating a blog and as a .NET programmer, a lot of my posts will be tagged with ".net".  I noticed that when generating a paginator for this tag, the link to the next page is incorrect.

The initial page is generated as:

```
http://localhost:1313/tags/.net/
```

But the "Next" link is:

```
http://localhost:1313/tags/index.net/page/2
```

When it should be:

```
http://localhost:1313/tags/.net/page/2
```

Not sure where the extra "index" is coming from.

**Comment by bep** [comment] 2016-04-27 07:09
I suspect this is fixed in Hugo 0.16-DEV, though. You are using hugo 0.15, right?

**Comment by patrick-steele** [comment] 2016-04-27 11:46
Yeah, sorry.  Forgot to include the version number.  This was 0.15.

I'll see if I can get it built locally and re-test. Would that be the `pre16` branch?

**Comment by moorereason** [comment] 2016-04-27 12:53
No, it's the `master` branch.

**Comment by shapeshed** [comment] 2016-08-03 10:48
This is also an issue for me on 0.16. 

|I have tag of `node.js` in my front matter.

```json
  "tags": [
    "Node.js"
  ]
```

The initial page is ok `/tags/node.js/` but the paginated links are `/tags/node/index.js/page/2`

**Comment by bep** [comment] 2017-02-28 19:09
This issue has been automatically marked as stale because it has not been commented on for at least four months.

The resources of the Hugo team are limited, and so we are asking for your help.

If this is a **bug** and you can still reproduce this error on the <code>master</code> branch, please reply with all of the information you have about it in order to keep the issue open.

If this is a **feature request**, and you feel that it is still valuable, please open a proposal at https://discuss.gohugo.io/.

This issue will automatically be closed in four months if no further activity occurs. Thank you for all your contributions.

**Comment by bep** [comment] 2017-03-01 09:22
**Note/Update:** This issue is marked as stale, and I may have said something earlier about "opening a thread on the discussion forum". Please don't.

If this is a **bug** and you can still reproduce this error on the latest <code>release</code> or the <code>master</code> branch, please reply with all of the information you have about it in order to keep the issue open.

If this is a **feature request**, and you feel that it is still relevant and valuable, please tell us why.

**Comment by shapeshed** [comment] 2017-03-01 12:45
hey @bep. tested this against `master`. yes this is still an issue. categories with `.` within the string (e.g. `Node.js`) causes rendering and pagination to break.

I have created a test case repository here with replication steps. 
https://github.com/shapeshed/hugo-2110

**Closed** 2017-03-27 13:44 UTC
Labels: Bug, Keep
