### ISSUE TITLE
figure caption text displayed in .Summary

### ISSUE THREAD

**Issue by subfxnet** [spf13/hugo#2982] opened 2017-01-22 23:33 UTC
If I put a figure shortcode as the first line in my content (after frontmatter) with a caption="" attribute, the caption text is captured in .Summary.

Hugo version: 0.18.1

**Comment by moorereason** [comment] 2017-01-23 02:28
Dupe of #1503

**Closed by moorereason** 2017-01-23 02:28 UTC
Labels: Duplicate

**Comment by subfxnet** [comment] 2017-01-23 14:19
Apologies, I didn't look that far back in the issue list.
