### ISSUE TITLE
Cannot see updated files from public/  in VirtualBox shared folders

### ISSUE THREAD

**Issue by itoed** [spf13/hugo#841] opened 2015-01-26 04:51 UTC
When running `hugo server` from a VirtualBox shared folder, updated files cannot be served.

Here is a Vagrant project that can reproduce the situation: https://github.com/itoed/hugo-virtualbox.

After you run the server and navigate to the Hugo site, try to edit some content and restart the server.  The contents of `public/` will be updated accordingly, but if you browse or curl the site, the new files will not be available.

However, if you stop the server, delete `public/`, then start the server, the updates become available.

My best guess is that this is due to the [VirtualBox bug with the sendfile syscall](https://www.virtualbox.org/ticket/9069).  The workaround on Apache and Nginx for this bug is to [disable sendfile](https://docs.vagrantup.com/v2/synced-folders/virtualbox.html).

If this is the cause affecting the Hugo server, is it possible to, say, have a command line option to disable sendfile?  Or are there any other workarounds that can allow me to develop a Hugo site within VirtualBox shared folders without deleting `public/`?

**Comment by anthonyfok** [comment] 2015-01-26 13:11
Hi @itoed,

Thank you for

**Comment by anthonyfok** [comment] 2015-01-26 13:31
Hi @itoed,

Thank you for your elaborate bug report and analysis.  Yes, I think you have hit the nail on the head!  I am able to reproduce this problem with your Vagrant project, and was able to get `hugo -w server` to show the updated `public/` files correctly if I were to do this:

1. Edit [$GOROOT/src/net/tcpsock_posix.go](http://golang.org/src/net/tcpsock_posix.go#L67) from Go 1.4.1, find `func (c *TCPConn) ReadFrom(r io.Reader) (int64, error)` around line 67, and force it to skip sendFile() and run run `genericReadFrom()` instead:

    ```
// ReadFrom implements the io.ReaderFrom ReadFrom method.
func (c *TCPConn) ReadFrom(r io.Reader) (int64, error) {
    /*
        if n, err, handled := sendFile(c.fd, r); handled {
                return n, err
        }
    */
        return genericReadFrom(c, r)
}
```
2. `rm -f $GOROOT/pkg/linux_amd64/net.a`
3. `go get -v github.com/spf13/hugo` which fetches the latest Hugo v0.13-DEV source, and rebuilds `net` and `hugo`
4. `$GOPATH/bin/hugo -w server`

I think this is best fixed in Go's core net library.  If you are in a hurry to get it fixed and working, please try the procedure above.

**Comment by itoed** [comment] 2015-01-26 19:05
Hi Anthony,

Thank you so much for taking the initiative to get this working.  And for taking the time to provide a workaround.

Since configuring Hugo is not going to be a solution, feel free to mark this issue closed if it's not needed.

Have a good one!

**Comment by anthonyfok** [comment] 2015-01-26 21:15
Thanks @itoed for discovering and bringing up this issue.  Ultimately, the solution happening at https://github.com/golang/go/issues/9694 will be useful to all Go users doing development with Vagrant on VirtualBox.

I think we will keep this issue open to help us keep track of the progress of https://github.com/golang/go/issues/9694.  It would be interesting to see how the upstream Go developers fix this issue.  (I am too new to Go to offer concrete code, and can only write some pseudo-pseudocode, though I may try to learn more and play with it tonight.)

**Comment by c4milo** [comment] 2015-01-26 22:22
Guys, please explore using NFS shared folders instead: http://docs-v1.vagrantup.com/v1/docs/nfs.html. I highly doubt something in Go will be fixed as the issue lives in VirtualBox.

**Comment by bjornerik** [comment] 2015-01-26 22:40
This is clearly not a Hugo issue.

**Closed by bjornerik** 2015-01-26 22:40 UTC
Labels: enhancement

**Comment by anthonyfok** [comment] 2015-01-27 05:11
What I am concerned, however, is how many people would actually run Hugo inside Vagrant with VirtualBox.  Is it a common use case nowadays?  Or not really?  Of course, the ideal here is to remove any obstacles to using Hugo, though I agree that it is a delicate balance.

Anyhow, back to this issue report:  Ultimately, the issue lies with VirtualBox, and it is really a shame that VirtualBox being such wonderful software, such a bug can be ignored and left unanswered for 3 years, and Nginx (and probably Apache) had to give in and implement such "EnableSendfile off" kludge, for better or for worse...  Oh well, that's life, I guess.  :-)

I've better stop ranting.  :-)

**Comment by bjornerik** [comment] 2015-01-27 08:16
Well, if Hugo should solve EVERYTHING, we should hire a bunch of support people. If VirtualBox have slept on this for years, well ... who can expect us to fix?

**Comment by anthonyfok** [comment] 2015-01-27 08:18
@bjornerik: I totally agree with you.  :wink:

**Comment by conradwt** [comment] 2015-01-27 09:18
@anthonyfok In general, this is open source and people should be willing to contribute in some way.  This can be in the form of a bug report, patch, and/or project documentation. Next, I would prefer that the Hugo project focuses on the 4 major operating systems supported by the Go Language:  Mac, Linux, FreeBSD, and Windows.  Furthermore, the support of the various virtualization platforms (i.e. VirtualBox, VMWare, and so on) should be a secondary concern unless others who want/need this functionality are willing to work with these virtualization providers to resolve these issues.  In short, open-source works best when it focuses on the core goals of the project and receive the contribution of others within the community.

**Comment by anthonyfok** [comment] 2015-01-27 10:50
@conradwt, you have summed it up wonderfully!  Thank you!  Let's focus on our core goals.

**Comment by criscola** [comment] 2018-03-22 14:23
Pinging this issue because this is still a problem... I guess it's time to simply uninstall vagrant, or am I missing something?
