### ISSUE TITLE
html/template:  on range loop re-entry: ambiguous URL context

### ISSUE THREAD

**Issue by alrayyes** [spf13/hugo#2514] opened 2016-10-01 23:42 UTC
Hi there,

The following code produces an error on build:

``` html
<div class="cover-card col-sm-4" style="background: url({{ range last 1 .image }}{{ if index . "#text" }}{{ index . "#text" }}{{ else  }}http://img2-ak.lst.fm/i/u/300x300/c6f59c1e5e7240a4c0d427abd71f3dbb.png{{ end }}{{ end }}) no-repeat center top;background-size:cover;">
```

Namely

``` shell
Started building site
ERROR: 2016/10/02 01:27:26 general.go:222: Error while rendering homepage: html/template:theme/index.html:35:116: on range loop re-entry: {{index . "#text"}} appears in an ambiguous URL context
```

This workaround fixes it for some reason:

``` html
{{ range last 1 .image }}<div class="cover-card col-sm-4" style="background: url({{ if index . "#text" }}{{ index . "#text" }}{{ else  }}http://img2-ak.lst.fm/i/u/300x300/c6f59c1e5e7240a4c0d427abd71f3dbb.png{{ end }}) no-repeat center top;background-size:cover;">{{ end }}
```

Full template code can be found [here](https://github.com/alrayyes/lastfm-hugo-demo-theme/blob/master/layouts/index.html).

Is this a Hugo bug or am I doing something wrong?

**Comment by bep** [comment] 2016-10-02 09:06
This smells like a bug in the Go stdlib.

What version of Hugo? OS? If built self, what Go version?

**Comment by alrayyes** [comment] 2016-10-02 11:57
Hugo version:

```shell
 Hugo Static Site Generator v0.16 BuildDate: 2016-06-06T14:37:59+02:00
```

Go version:

```shell
go version go1.7.1 darwin/amd64
```

Although I have the same issue in [my deployment docker container](https://hub.docker.com/r/andthensome/alpine-hugo-git-bash/) which is based on Alpine Hugo 0.16 as well.

**Comment by bep** [comment] 2016-10-02 15:34
On and added note:

```
{{ if index . "#text" }}
```

The `index` func doesn't support indexing of slices with strings, so the above will also fail if executed.

**Comment by bep** [comment] 2016-10-02 16:07
https://github.com/golang/go/issues/17319

**Comment by bep** [comment] 2016-10-02 18:15
OK, I may not understand what `.image` is, but it doesn't matter -- I have reported the real issue with the Go team.

**Comment by alrayyes** [comment] 2016-10-02 19:44
It basically just parses a json file. For example:

```json
{
  "recenttracks": {
    "track": [{
      "artist": {
        "#text": "Tame Impala",
        "mbid": "63aa26c3-d59b-4da4-84ac-716b54f1ef4d"
      },
      "name": "New Person, Same Old Mistakes",
      "streamable": "0",
      "mbid": "",
      "album": {
        "#text": "Currents",
        "mbid": ""
      },
      "url": "https://www.last.fm/music/Tame+Impala/_/New+Person,+Same+Old+Mistakes",
      "image": [{
        "#text": "https://lastfm-img2.akamaized.net/i/u/34s/dd45b0438a315aed98b5830aa2fc43c5.png",
        "size": "small"
      }, {
        "#text": "https://lastfm-img2.akamaized.net/i/u/64s/dd45b0438a315aed98b5830aa2fc43c5.png",
        "size": "medium"
      }, {
        "#text": "https://lastfm-img2.akamaized.net/i/u/174s/dd45b0438a315aed98b5830aa2fc43c5.png",
        "size": "large"
      }, {
        "#text": "https://lastfm-img2.akamaized.net/i/u/300x300/dd45b0438a315aed98b5830aa2fc43c5.png",
        "size": "extralarge"
      }],
      "date": {
        "uts": "1475416114",
        "#text": "02 Oct 2016, 13:48"
      }
    }, {
      "artist": {
        "#text": "Tame Impala",
        "mbid": "63aa26c3-d59b-4da4-84ac-716b54f1ef4d"
      },
      "name": "Love/Paranoia",
      "streamable": "0",
      "mbid": "",
      "album": {
        "#text": "Currents",
        "mbid": ""
      },
      "url": "https://www.last.fm/music/Tame+Impala/_/Love%2FParanoia",
      "image": [{
        "#text": "https://lastfm-img2.akamaized.net/i/u/34s/dd45b0438a315aed98b5830aa2fc43c5.png",
        "size": "small"
      }, {
        "#text": "https://lastfm-img2.akamaized.net/i/u/64s/dd45b0438a315aed98b5830aa2fc43c5.png",
        "size": "medium"
      }, {
        "#text": "https://lastfm-img2.akamaized.net/i/u/174s/dd45b0438a315aed98b5830aa2fc43c5.png",
        "size": "large"
      }, {
        "#text": "https://lastfm-img2.akamaized.net/i/u/300x300/dd45b0438a315aed98b5830aa2fc43c5.png",
        "size": "extralarge"
      }],
      "date": {
        "uts": "1475415754",
        "#text": "02 Oct 2016, 13:42"
      }
    }],
    "@attr": {
      "user": "alrayyes",
      "page": "1",
      "perPage": "2",
      "totalPages": "87521",
      "total": "175042"
    }
  }
}
```

And sometimes #text isn't set. Because of the '#' I couldn't figure out another way to check if it exists.

**Comment by bep** [comment] 2016-10-02 20:42
Ah, ok -- yes, then your construct is correct. But you found what I consider a bug in the Go stdlib and that is good.

**Comment by alrayyes** [comment] 2016-10-02 20:45
I'm glad I can be of service. Hopefully there will be many more to come with some decent commentary, once I become more proficient in Go.

**Comment by moorereason** [comment] 2016-12-28 04:11
The issue is that you have a `range` within the `url(...)` context, which can create ambiguities in the URL validation in the Go template engine.  You can work around the issue, as you already discovered, by putting the `range` outside the URL context.

It doesn't look like this behavior will be changed upstream, so I'm closing.

**Closed by moorereason** 2016-12-28 04:11 UTC
Labels: kind/bug, status/upstream
