### ISSUE TITLE
Allow to specify Markdown within templates

### ISSUE THREAD

**Issue by gunnarmorling** [spf13/hugo#2848] opened 2016-12-28 22:05 UTC
Homepages typically have a complex structure comprising mark-up (e.g. styled `<div>`) as well as content sections. For the former plain HTML is suitable, for the latter Markdown often is preferrable. In a home page with complex layout the contents will be scattered across several parts, though, and hence cannot be fetched from a single Markdown file. It'd thus be desirable to have one or both of the following two features:

* Allow to use Markdown sections within a template for simply inline creation of "contents" parts, e.g.

    {{ markdownify }}
    ** my markdown **
    {{ end }}

* Provide a way to include contents from multiple named Markdown files into the "slots" of a template.

A work-around for the latter has been described in [this discussion](https://discuss.gohugo.io/t/load-multiple-content-files-in-a-single-template/2566).

**Comment by moorereason** [comment] 2016-12-28 22:14
Thanks for your feedback.  I'm going to close this as a dupe of #2830.  We hope to eventually allow a page to be defined by a directory of content instead of a single content file.  That would solve your issue.

Until then, most people put their Markdown in frontmatter variables and then use `{{ markdownify .Params.whatever }}`.

**Closed by moorereason** 2016-12-28 22:14 UTC
Labels: status/duplicate
