### ISSUE TITLE
org-mode file parsing treating every line of text as a new paragraph

### ISSUE THREAD

**Issue by bstamour** [spf13/hugo#3126] opened 2017-03-03 16:20 UTC
I'm trying to create a blog post using the org file format, but every line of text is being wrapped with paragraph tags, thus giving the generated output a very strange appearance. If I change the file extension to .md instead of .org everything looks fine (for now I am just using text, no headers, lists, etc.)

**Comment by moorereason** [comment] 2017-03-03 16:34
Cc: @chaseadamsio

**Comment by bep** [comment] 2017-03-03 16:35
See https://github.com/chaseadamsio/goorgeous/issues/26

**Comment by chaseadamsio** [comment] 2017-03-03 17:42
Should have this fixed after this weekend. I've been doing a lexer/parser rewrite this week. Thanks for cc'ing @moorereason & sharing the open issue @bep.

**Comment by gour** [comment] 2017-03-20 11:13
Ahh...shortly after posting to the Hugo [forum](https://discuss.gohugo.io/t/org-mode-and-fill-paragraph-problem/5858) I've discovered the issue is already known. :sad

**Comment by bep** [comment] 2017-04-02 22:40
Fixed by d122260

**Closed by bep** 2017-04-02 22:40 UTC
Labels: Upstream
