### ISSUE TITLE
Add org-mode support

### ISSUE THREAD

**Issue by eggcaker** [spf13/hugo#936] opened 2015-03-01 01:04 UTC
is possible to write content with org-mode markup ? then compile with pandoc or something else ?

**Comment by bep** [comment] 2015-03-01 01:08
Use http://discuss.gohugo.io/

**Comment by priyadarshan** [comment] 2015-04-03 14:48
I'm sure many would be interested. For now, I have found this: http://www.personal.psu.edu/bam49/notebook/org-to-hugo/

**Comment by bep** [comment] 2015-04-03 18:40
See #333

**Comment by digitalcraftsman** [comment] 2017-01-24 15:01
This issue is more or less a duplicate of #1483 since both request the support for orgmode. This request the support via a third-party tool (pandoc), #1483 suggests to use a Go-native application.

**Closed** 2017-01-24 15:21 UTC
Labels: Enhancement
