### ISSUE TITLE
Upper case content url and folder generate lowercase url for links

### ISSUE THREAD

**Issue by oohazard2** [spf13/hugo#1329] opened 2015-08-06 10:16 UTC
as mentionned here : http://discuss.gohugo.io/t/upper-case-urls/1525

I have been porting my old blog to hugo

Since I want to keep using the same exact urls and some of thes posts have upper case letter in the url, I wanted hugo to generate folder with upper case letter

I managed to do that only by using the url option in the frontmatter of the respective posts.

This create folder with upper case letter properly.

Unfortunately the url generated for links in the template are all lower case. so when clciking upon these links it goes to nowhere

Thanks

**Comment by moorereason** [comment] 2015-08-10 18:43
Isn't this a duplicate of Issue #557?

**Comment by bep** [comment] 2015-08-10 18:45
Yes.

**Closed by bep** 2015-08-10 18:45 UTC
