### ISSUE TITLE
highlighting doesn't work for .html files & CDATA not respected in md

### ISSUE THREAD

**Issue by Dieterbe** [spf13/hugo#1102] opened 2015-05-04 02:07 UTC
i just noticed that if i store my posts as foo.html, then ` {{< highlight bash >}}... bash code...{{< /highlight >}}` is ignored.
if i rename to foo.md, then pygmentize is correctly invoked and runs syntax highlighting.

a related problem is that after switching to foo.md naming, `<![CDATA[` and `]]>` markers are literally included.
in html, you can use CDATA to mean "literal data" without having to encode entities etc. i use this liberally for code (which needs syntax highlighting). the markers themselves however should not be rendered.

not sure what's the best approach here?
* make pygmentize work for .html content?
* respect CDATA markers in markdown (is markdown supposed to accept anything html accepts?)

thanks

**Comment by bep** [comment] 2015-05-04 08:07
Your main topic is a duplicate of #674.

Create a new issue for the second one. An issue report that mingles totally unrelated issues into one is impossible to handle.

**Closed by bep** 2015-05-04 08:07 UTC
