### ISSUE TITLE
Taxonomies ignoring uglyurl=true

### ISSUE THREAD

**Issue by sidewinder12s** [spf13/hugo#1989] opened 2016-03-18 02:46 UTC
Not sure if this is intended but when uglyurls is set to true the generated taxonomy pages do not have uglyurls, they still use just folders instead of making all the links pointed directly to files.

**Comment by GiovanniMoretti** [comment] 2016-04-12 13:48
To be specific, the links to posts are in the uglyURL form - i.e. the link does end in  _.html_.
However the links to categories and tags are still in the form as if **uglyurl=false** - i.e. they point to directories, not to HTML files.

Unfortunately, the folder being pointed at  (e.g. *http://localhost:1313/categories/general/*) contains an *index.xml* and a *page* subdirectory, but no HTML file so doesn't render anything.

It turns out that at individual category and tag pages are being generated correctly, but the links are wrong.

e.g. the link to the *general* category is
```
       http://localhost:1313/categories/general/           But it should be 
       http://localhost:1313/categories/general.html 
```

Likewise the tags link (e.g. for tag 'linux')
```
      http://localhost:1313/tags/linux/                    And this should be
      http://localhost:1313/tags/linux.html
```
I need the **uglyurls=true** option as I need to keep the rendered HTML files in their original directories (i.e. in same relative location next to images etc). 

If **uglyurls=false**, then the rendered HTML file is moved into its own directory breaking all the relative links that it contains.

The files in /content are generated by Emacs Orgmode's "Export to HTML" and look fine when rendered by Hugo, and the orgmode files are in the own directories with related images and other files i really don't want to shift, so it'd be great if the links to categories and tags when **uglyurls=false** option was fixed.

Then I get the power of orgmode with the benefits of Hugo :-)

Many thanks - Giovanni

**Comment by GiovanniMoretti** [comment] 2016-04-20 07:54
I've just written a little Python 3 program to patch the files in /public so the generated tag and category pages work correctly:
   https://gist.github.com/GiovanniMoretti/8c874652689960c9c11d81952c0ecbd6

**Comment by bep** [comment] 2016-04-20 08:14
I just tested this, and `uglyurls=true` works fine for taxonomies.

Not sure what you mean by "making all the links pointed directly to files".

Can you provide a concrete example?

**Comment by GiovanniMoretti** [comment] 2016-04-20 09:06
Thanks for checking. I've attached a file that has the **examples/blog** subdirectory from the Github source for Hugo, and I've added some more posts to the _/content/post_ directory, so there are a reasonable number of categories and tags.

What you see in the public directory is the output of "hugo" - I'm using Hugo v0.15 via Homebrew on a Macbook.

If you run 'hugo server' and have a look at the first post - it's in the General category (and so are lots of other pages) but the link is to  the _general_ directory which doesn't contain a HTML file so the displayed page is empty.

Another example, from the home page, scroll down to the post starting with **VP2E offcentre**. It's in the "Radio" category and has the tag "Antennas" (as do several other pages). Neither of the links on the right hand side of the page show the entries for the category or tag respectively.

Hopefully this concrete example helps. The only change to blog example was add the additional posts, and to add  _uglyurls = true_ to the config file.
[uglyURLtest.zip](https://github.com/spf13/hugo/files/227554/uglyURLtest.zip)

**Comment by bep** [comment] 2016-04-20 09:30
@GiovanniMoretti I looked at your site. The links are created by the template:

```
 <li><a href="/categories/{{ . | urlize }}">{{ . }}</a></li>
```

And the template is created by you or the theme author. I fail to see how Hugo could have fixed this one. 

If noone is able to provide an example where Hugo is "doing the wrong thing", I'm gonna close this.

**Comment by GiovanniMoretti** [comment] 2016-04-20 10:19
It's not my template. It's **the closest to a "canonical example" we can get,** (the _blog example_ from Hugo's source), given that Hugo doesn't supply a known correct sample theme/template.

Following your lead above, I've modified the template in _layouts/post/single_ so it now gives the correct URL (by adding **.html** to the end of the link):

                {{ range .Params.categories }}
                    <li><a href="/categories/{{ . | urlize }}.html">{{ . }}</a></li>
                {{ end }}

And both tags and categories now work. Thank you - I now understand what's going on.

I think this points to out an underlying problem, as most if not all of the themes I tried from the Hugo Theme gallery behaved in the same way, so either

1.  there needs to be a way for Hugo to generate the URL that includes the .html (or not) for the taxonomies, OR
2. theme authors should be encouraged to specify which setting of **uglyurl** their theme is designed for.

My modification of adding **.html** explicitly to the layout means it won't work for **uglyurls=false**. 

Is my modification to the layout what you were expecting or is there a more elegant way to make the category and tags links in a layout work correctly when **uglyurls=true** and and when **uglyurls=false**?  

Apologies if this blindingly obvious to you but I'm completely new to both Hugo and the templating language.

**Comment by bep** [comment] 2016-04-20 11:00
>Is my modification to the layout what you were expecting or is there a more elegant way to make the category and tags links in a layout work correctly when uglyurls=true and and when uglyurls=false? 

Currently no. I'll keep this open. This will be much easier once ...

https://discuss.gohugo.io/t/node-improvements/1593

... is done.

But currently I guess uglyURLs are for people that is in full control of their templates.

**Comment by mgedmin** [comment] 2016-05-31 10:00
Can templates even check whether uglyURLs is set to true?

Alternatively, what do you think about exposing the `URLizeAndPrep` function to the templates?

**Comment by bep** [comment] 2017-03-01 09:20
**Note/Update:** This issue is marked as stale, and I may have said something earlier about "opening a thread on the discussion forum". Please don't.

If this is a **bug** and you can still reproduce this error on the latest <code>release</code> or the <code>master</code> branch, please reply with all of the information you have about it in order to keep the issue open.

If this is a **feature request**, and you feel that it is still relevant and valuable, please tell us why.

**Closed** 2017-03-27 13:44 UTC
Labels: Enhancement
