### ISSUE TITLE
Nesting shortcodes result in spurious <p> tag

### ISSUE THREAD

**Issue by dechamps** [spf13/hugo#2134] opened 2016-05-08 11:42 UTC
Hugo version: 0.15

# Steps to reproduce:

Create a file `layout/shortcodes/shortcode.html` with contents:

    (BEGIN SHORTCODE) {{ .Inner }} (END SHORTCODE)

Create a file `content/post/links.md` with contents:

```Markdown
# OK

{{% shortcode %}}some content{{% /shortcode %}}

# Why the extra block?

{{% shortcode %}}outer {{% shortcode %}}nested{{% /shortcode %}} outer{{% /shortcode %}}
```

# Expected HTML output:

```HTML
<h1>OK</h1>
<p>foo (BEGIN SHORTCODE) some content (END SHORTCODE) bar</p>
<h1>Why the extra block?</h1>
<p>foo (BEGIN SHORTCODE) outer (BEGIN SHORTCODE) nested (END SHORTCODE) outer (END SHORTCODE) bar</p>
```

# Actual HTML output:

```HTML
<h1>OK</h1>
<p>foo (BEGIN SHORTCODE) some content (END SHORTCODE)
 bar</p>
<h1>Why the extra block?</h1>
<p>foo (BEGIN SHORTCODE) <p>outer (BEGIN SHORTCODE) nested (END SHORTCODE)
 outer</p>
 (END SHORTCODE)
 bar</p>
```

The extra `<p>` tag has nothing to do here and messes up the page layout. Also note the weird newlines.

# Workaround

This happens because Hugo is interpreting the newline at the end of the shortcode file too literally. The output if correct is the newline is removed from the shortcode file, for example by doing something like this:

```bash
echo -n "$(cat layouts/shortcodes/shortcode.html)" > layouts/shortcodes/shortcode2.html
mv layouts/shortcodes/shortcode2.html layouts/shortcodes/shortcode.html
```

(Another way is to use `:set binary noeol` before writing the file in vim)

This is too brittle - ideally Hugo should always ignore the last newline character at the end of shortcode files.

**Comment by bep** [comment] 2016-05-08 12:13
This is a duplicate of several others.

**Closed by bep** 2016-05-08 12:13 UTC
