### ISSUE TITLE
Hugo 0.16-DEV (Jan 2016) hangs if content/ is empty

### ISSUE THREAD

**Issue by jsloyer** [spf13/hugo#1797] opened 2016-01-28 15:12 UTC
I am running Hugo 0.16 on Travis and when I try to generate the site on Travis and Hugo hangs.  Eventually Travis times out and things terminate.

Hugo Version:
```
hugo version
Hugo Static Site Generator v0.16-DEV BuildDate: 2016-01-28T15:10:26Z
```

Output from running `hugo -v`.
```
hugo -v
INFO: 2016/01/28 15:10:27 hugo.go:385: Using config file: /home/travis/gopath/src/ghe/org/project/config.toml
INFO: 2016/01/28 15:10:27 hugo.go:501: syncing static files to /home/travis/gopath/src/ghe/org/project/public/
```

Relevant pieces from `.travis.yml`
```
language: go
go:
- '1.5'
sudo: true
dist: precise
group: edge
```

**Comment by jsloyer** [comment] 2016-01-28 15:32
Tested this out with v0.14, 0.15, both work fine.

**Comment by bep** [comment] 2016-01-29 00:07
We build the docs site on Travis as part of the CI, and that is currently green. Hmmm.... Could you try to update to the latest Go 1.5.3 (matching what we use on Travis)?

If it hangs on the "syncing ..." a suspect is one of @spf13 s latest commits.

**Comment by jsloyer** [comment] 2016-01-29 13:46
@bep just ran with with Go 1.5.3 and got the same hang...  I will note this is running on an on-prem instance of Travis not travis-ci.org.

**Comment by anthonyfok** [comment] 2016-01-29 22:38
@jsloyer: I was able to get `hugo` to hang right after a `hugo site new` run, i.e. a site where the `content/` directory is empty, on my Debian laptop.  Is that the case for you too?

**Comment by jsloyer** [comment] 2016-01-30 14:27
@anthonyfok yep!

**Comment by anthonyfok** [comment] 2016-01-30 16:45
Thanks @jsloyer!  I have changed the title of the issue accordingly.  :-)

Cheers,
Anthony

**Comment by tatsushid** [comment] 2016-01-31 14:48
According to `git bisect`, this problem seems to be introduced at bcc42c0. I can reproduce the issue in the way @anthonyfok mentioned from the commit.

**Comment by tatsushid** [comment] 2016-01-31 15:04
I think the root cause of the problem is the line https://github.com/spf13/hugo/blob/master/hugolib/site.go#L880 in `Site.ReadPagesFromSource()` method.

The [receiver in `Site.CreatePages`](https://github.com/spf13/hugo/blob/master/hugolib/site.go#L944) expects values from a channel but at the above line, it only returns `nil` and a channel value is never sent so Hugo hangs here.

**Comment by tatsushid** [comment] 2016-02-02 23:22
This should be fixed in 68e2e63.

**Comment by bep** [comment] 2016-02-07 14:37
This needs a test case, reopen.

**Comment by tatsushid** [comment] 2016-02-08 13:14
I added a test to this issue in 2b3b90a

**Closed** 2016-02-08 13:19 UTC
Labels: kind/bug
