### ISSUE TITLE
Add support for subsections with corresponding templates

### ISSUE THREAD

**Issue by desaiuditd** [spf13/hugo#455] opened 2014-08-30 11:35 UTC
I've a content on a site as below :
- .
  - content
    - sectionX
      - sub-sectionA
        - testCase1.md
        - testCase2.md
      - sub-sectionB
        - testCase3.md
        - testCase4.md
    - quote
      - first.md
      - second.md

So the problem is if I want to render a list of all posts under `sectionX` then `_default/list.html` does the trick. And all the posts (testCase1, testCase2, testCase3, testCase4) gets displayed.
But if I want to list down only the posts under `sub-SectionA` or `sub-sectionB`, which template should I go for ?
By default, it just renders the links of the posts under that category. It seems that it is not taking up any available template or my guess is that the template it seeks is not available in my layout folder.

**Comment by waddlesplash** [comment] 2016-08-07 18:32
Quick note: I'm moving a major site off of Drupal onto Hugo, and on Drupal there were blogs that could be paginated by themselves (e.g. `/blog/` showed all the blogposts, but `/blog/somebody/` showed and paginated only posts by `somebody`.) Since Hugo doesn't have subsections yet, I can't make the `/blog/somebody/` part paginated, which is rather annoying (and makes some pages overly long.)

**Comment by alizain** [comment] 2016-08-26 16:05
This would really be fantastic

**Comment by runloop** [comment] 2017-02-16 23:03
I just spent a load of time inputting my content thinking that I would be able to access my sub-folders only to find out: no. This should be a no brainer.

> Hugo believes that you organize your content with a purpose. The same structure that works to organize your source content is used to organize the rendered site.

Except without subsections this is not really true as there is no way to list subsection content without duplicating information found in the path, in the front matter. 

This would be an awesome feature, but I'm not going to hold my breath.

**Comment by abnodes** [comment] 2017-03-04 20:49
Any update, My development has now had to stop on this as it should be a given really that this feature should be there.

**Comment by bep** [comment] 2017-03-04 20:52
This feature has been pushed to Hugo 0.21 -- in line with the wishes of the Hugo community at http://discuss.gohugo.io

**Comment by bep** [comment] 2017-03-04 20:52
Duplicate of #465

**Closed by bep** 2017-03-04 20:52 UTC
Labels: Enhancement

**Comment by DaniloGomez** [comment] 2019-09-06 19:25
What I'm doing to list subsections is to have them "plain" in the directory tree just as subsections and then rename their URLs.

So, to make the `public` directory tree to look like this:
```
public/
+-- index.html                # listed by layout/index.html
+-- section-1/
|   +-- index.html            # listed by layout/section-1/list.html
|   +-- subsection-a/
|   |   +-- index.html        # listed by layout/section-1_subsection-a/list.html
|   +-- subsection-b/
|   |   +-- index.html        # listed by layout/section-1_subsection-b/list.html
|   +-- subsection-c/
|       +-- index.html        # listed by layout/_default/list.html
+-- section-2/
    +-- index.html            # listed by layout/section-2/list.html
```

* I set `layout` and `content` directories like this (with "flattened" subsections):
```
content/
+-- _index.md                 # index from /
+-- section1/
|   +-- _index.md             # index from /section-1
+-- section-1_subsection-a/
|   +-- _index.md             # index from /section-1/subsection-a
+-- section-1_subsection-b/
|   +-- _index.md             # index from /section-1/subsection-b
+-- section-1_subsection-c/
|   +-- _index.md             # index from /section-1/subsection-c
+-- section2/
    +-- _index.md             # index from /section-2
layout/
+-- index.html
+-- _default/
|   +-- list.html
+-- section1/
|   +-- list.html
+-- section-1_subsection-a/
|   +-- list.html
+-- section-1_subsection-b/
|   +-- list.html
+-- section2/
    +-- list.html
```

* And then I rewrote subsections URLs in their front matters.

```
+++
# section-1_subsection-a/_index.md
url = "/section-1/subsection-a"
+++
```
```
+++
# section-1_subsection-b/_index.md
url = "/section-1/subsection-b"
+++
```
```
+++
# section-1_subsection-c/_index.md
url = "/section-1/subsection-c"
+++
```
